name: places_api
description: Places api from google.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.0
  json_annotation: ^4.4.0
  meta: ^1.3.0
  very_good_analysis: ^2.1.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0